[versions]
aurora = "0.0.37-SNAPSHOT"
coroutines = "1.5.0"
hilt = "2.37"
moshix = "0.11.2"
retrofit = "2.9.0"
sqldelight = "1.5.0"

[libraries]

kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-jvm = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm", version.ref = "coroutines" }

androidx-activity-compose = "androidx.activity:activity-compose:1.3.0-beta01"
androidx-appcompat = "androidx.appcompat:appcompat:1.4.0-alpha02"
androidx-browser = "androidx.browser:browser:1.3.0"
androidx-paging-compose = "androidx.paging:paging-compose:1.0.0-alpha10"

aurora-skin = { module = "org.pushing-pixels:aurora-skin", version.ref = "aurora" }
aurora-icon = { module = "org.pushing-pixels:aurora-icon-icon", version.ref = "aurora" }
aurora-component = { module = "org.pushing-pixels:aurora-component", version.ref = "aurora" }
aurora-window = { module = "org.pushing-pixels:aurora-window", version.ref = "aurora" }

dagger-hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
dagger-hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
dagger-hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }

moshi-lib = "com.squareup.moshi:moshi:1.12.0"
moshix-ksp = { module = "dev.zacsweers.moshix:moshi-ksp", version.ref = "moshix" }
moshix-metadatareflect = { module = "dev.zacsweers.moshix:moshi-metadata-reflect", version.ref = "moshix" }

retrofit-lib = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshiConverter = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }

sqldelight-jvmDriver = { module = "com.squareup.sqldelight:sqlite-driver", version.ref = "sqldelight" }
sqldelight-androidDriver = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }

testing-mockWebServer = "com.squareup.okhttp3:mockwebserver3-junit4:5.0.0-alpha.2"
